# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use 'bundle exec jekyll serve'.
# If you change this file, please restart the server process.

# Site setings
name: 'pewmed'
description: 'Draw the future of the medicine.'
# Sidebar about text
site_description: 'We connect AI and healthcare, and draw the future of the medicine.'
logo: # path of site logo, e.g. "assets/images/images/logo.png"
favicon: 'assets/images/favicon.ico'
baseurl: # the subpath of your site, e.g. "/blog"
production_url: https://curious-jekyll.netlify.com/
disqus: 'justgoodthemes'
mailchimp_url: '//justgoodthemes.us3.list-manage.com/subscribe/post?u=78f1bab16028354caeb23aecd&amp;id=4a7330d117'
ga_analytics: # Google Analytics id, e.g. "UA-NNNNNNNN-N"

# Contact form setings
email: pewmed@gmail.com
contact_page_description: "If you have any questions, suggestions, or comments, please leave a message below."
thankyou_page_description: "Your message has been successfully sent. We will contact you very soon!"

# Contacts section in the sidebar
sidebar_widget_description: "Connecting medicine with engineering, we dream of a better future."
sidebar_widget_email: "pewmed@ gmail.com"
sidebar_widget_address: "Seoul, Korea"
sidebar_widget_phone: "+123 112 23445"


# Social links
twitter: 'JustGoodThemes'
facebook: 'username'
github: 'JustGoodThemes'
codepen: 'username'
dribbble: 'username'
medium: '@username'
instagram: 'pewmed'
pinterest: 'username'
linkedin: 'username'

# Navigation
navigation:
  - text: About
    url: /about/
  - text: Style Guide
    url: /style-guide/
  - text: Contact Me
    url: /contact/

# Required Plugins
plugins_dir:
  - jekyll-author-page
  - jekyll-paginate
  - jekyll-tagsgenerator
  - jekyll-seo-tag
  - jekyll-sitemap
  - sidenote

# Pagination
paginate: 6
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
